[project]
name = "horusdemodlib"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "audioop-lts>=0.2.2 ; python_full_version >= '3.13'",
    "crcmod>=1.7",
    "numpy>=2.3.4",
    "python-dateutil>=2.9.0.post0",
    "requests>=2.32.5",
]
